services:
  backend:
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    build: ./backend
    container_name: cue-backend
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - default
      - dev-infrastructure
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    container_name: cue-frontend
    ports:
      - "127.0.0.1:5173:80"
    networks:
      - default
    restart: unless-stopped

  worker-webserver:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: unless-stopped
    command:
      [
        "dagster-webserver",
        "-h",
        "0.0.0.0",
        "-p",
        "3000",
        "-m",
        "orchestrator.definitions",
      ]
    env_file:
      - ./worker/.env
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - default
      - dev-infrastructure
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - backend

  worker-daemon:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["dagster-daemon", "run"]
    env_file:
      - ./worker/.env
    networks:
      - default
      - dev-infrastructure
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - backend

volumes:
  dagster_home:

networks:
  dev-infrastructure:
    external: true
