services:
  backend:
    image: ghcr.io/tomdupont72/cue-backend:${APP_VERSION:-latest}
    container_name: cue-backend
    env_file:
      - /etc/cue-api.env
    ports:
      - "127.0.0.1:8004:8000"
    networks:
      - cue
      - infrastructure
    restart: unless-stopped

  frontend:
    image: ghcr.io/tomdupont72/cue-frontend:${APP_VERSION:-latest}
    container_name: cue-frontend
    ports:
      - "127.0.0.1:5177:80"
    networks:
      - cue
    restart: unless-stopped

  worker-webserver:
    image: ghcr.io/tomdupont72/cue-worker:${APP_VERSION:-latest}
    container_name: cue-worker-webserver
    restart: unless-stopped
    command:
      [
        "dagster-webserver",
        "-h",
        "0.0.0.0",
        "-p",
        "3000",
        "-m",
        "orchestrator.definitions",
      ]
    env_file:
      - /etc/cue-worker.env
    ports:
      - "127.0.0.1:3001:3000"
    networks:
      - cue
      - infrastructure
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - backend

  worker-daemon:
    image: ghcr.io/tomdupont72/cue-worker:${APP_VERSION:-latest}
    container_name: cue-worker-daemon
    restart: unless-stopped
    command: ["dagster-daemon", "run"]
    env_file:
      - /etc/cue-worker.env
    networks:
      - cue
      - infrastructure
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - backend

volumes:
  dagster_home:

networks:
  cue:
  infrastructure:
    external: true